version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./packages/web/dist/:/usr/share/nginx/html
    networks:
      app:
        ipv4_address: 10.8.0.6

  web:
    build: ./packages/web
    #ports:
    #- "4321:4321"
    volumes:
      - ./packages/web:/app
    env_file:
      - .env
    networks:
      app:
        ipv4_address: 10.8.0.5

  app:
    build: ./packages/app
    #ports:
    #- "4321:4321"
    volumes:
      - ./packages/app:/app
    env_file:
      - .env
    networks:
      app:
        ipv4_address: 10.8.0.4

  core:
    build: ./packages/core
    #ports:
    # - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    volumes:
      - ./packages/core:/app
    env_file:
      - .env

    networks:
      app:
        ipv4_address: 10.8.0.3

  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "${DB_HOST}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPY_PASSWORD: "1"
    healthcheck:
      test: ["CMD", "mysqladmin", "-u${DB_USER}", "-p${DB_PASSWORD}", "ping"]
      retries: 3
      timeout: 5s
    networks:
      app:
        ipv4_address: 10.8.0.2

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1
